# ML LAB - 3
# Name: Daksh Khandelwal
# Roll no- 45
# Batch- B_B3

In [14]:
import pandas as pd

dataset = pd.read_csv("enjoy.csv")
print(dataset)

      Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0   Sunny    Warm   Normal  Strong  Warm     Same        Yes
1   Sunny    Warm     High  Strong  Warm     Same        Yes
2   Rainy    Cold     High  Strong  Warm   Change         No
3   Sunny    Warm     High  Strong  Cool   Change        Yes
4   Sunny    Cold   Normal    Weak  Warm     Same         No
5  Cloudy    Warm   Normal    Weak  Warm     Same         No
6   Sunny    Warm   Normal    Weak  Cool     Same        Yes
7   Rainy    Warm     High    Weak  Cool   Change         No
8   Sunny    Warm   Normal  Strong  Cool     Same        Yes
9   Sunny    Warm     High    Weak  Warm     Same        Yes

In [15]:
dataset.head()

     Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes
4  Sunny    Cold   Normal    Weak  Warm     Same         No

In [16]:
dataset.tail()

      Sky AirTemp Humidity    Wind Water Forecast EnjoySport
5  Cloudy    Warm   Normal    Weak  Warm     Same         No
6   Sunny    Warm   Normal    Weak  Cool     Same        Yes
7   Rainy    Warm     High    Weak  Cool   Change         No
8   Sunny    Warm   Normal  Strong  Cool     Same        Yes
9   Sunny    Warm     High    Weak  Warm     Same        Yes

In [17]:
x= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

In [18]:
import pandas as pd

dataset = pd.read_csv("enjoy.csv")

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


def find_s(X, y):

    hypothesis = None
    print("Initial Hypothesis :", hypothesis)

    for i in range(len(X)):
        if y[i] == "Yes":

            if hypothesis is None:
                hypothesis = X[i].copy()

            else:
                for j in range(len(hypothesis)):
                    if hypothesis[j] != X[i][j]:
                        hypothesis[j] = "?"

        print(f"\nAfter Training Example {i+1}")
        print(hypothesis)

    return hypothesis


final_hypothesis = find_s(X, y)

print("\nFinal Hypothesis")
print(final_hypothesis)

Initial Hypothesis : None

After Training Example 1
['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']

After Training Example 2
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After Training Example 3
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

After Training Example 4
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 5
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 6
['Sunny' 'Warm' '?' 'Strong' '?' '?']

After Training Example 7
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 8
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 9
['Sunny' 'Warm' '?' '?' '?' '?']

After Training Example 10
['Sunny' 'Warm' '?' '?' '?' '?']

Final Hypothesis
['Sunny' 'Warm' '?' '?' '?' '?']

In [25]:
def candidate_elimination(concepts,target):
    specific = concepts[0].copy()
    general = [["?" for i in range(len(specific))]]
    print("\n Initial S : ",specific)
    print("initial G : ",general)
    for i,h in enumerate(concepts):
        if target[i] =="Yes":
            for x in range(len(specific)):
                if h[x] != specific[x]:
                    specific[x]="?"
        else:
            for x in range(len(specific)):
                if h[x] != specific[x]:
                    general.append(["?" if j!= x else specific[x] for j in range(len(specific))])
        print("\n Example", i+1)
        print("s= ",specific)
        print("G= ",general)
    return specific,general
S,G=candidate_elimination(X,y)
print("\n Final specific boundary:")
print(S)
print("\nFinal general boundary:")
print(G)

 Initial S :  ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
initial G :  [['?', '?', '?', '?', '?', '?']]

 Example 1
s=  ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
G=  [['?', '?', '?', '?', '?', '?']]

 Example 2
s=  ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
G=  [['?', '?', '?', '?', '?', '?']]

 Example 3
s=  ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
G=  [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]

 Example 4
s=  ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G=  [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]

 Example 5
s=  ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G=  [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

 Example 6
s=  ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G=  [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

 Example 7
s=  ['Sunny' 'Warm' '?' '?' '?' '?']
G=  [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

 Example 8
s=  ['Sunny' 'Warm' '?' '?' '?' '?']
G=  [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

 Example 9
s=  ['Sunny' 'Warm' '?' '?' '?' '?']
G=  [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

 Example 10
s=  ['Sunny' 'Warm' '?' '?' '?' '?']
G=  [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

 Final specific boundary:
['Sunny' 'Warm' '?' '?' '?' '?']

Final general boundary:
[['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]